---

- name: Restore tokens
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Stop Scylla service
      service:
        name: scylla-server
        state: stopped

    - name: Remove Scylla directories
      file:
        path: "/var/lib/scylla/{{ item }}"
        state: absent
      loop:
        - data
        - commitlog
        - hints
        - view_hints

    - name: Recreate Scylla directories
      file:
        path: "/var/lib/scylla/{{ item }}"
        state: directory
        owner: scylla
        group: scylla
        mode: 0755
      loop:
        - data
        - commitlog
        - hints
        - view_hints

    - name: Get seeds list
      shell: |
        grep '\- seeds:' /etc/scylla/scylla.yaml | awk '{ print $NF }' | tr -d '"' | tr -d "'"
      register: _seeds

    - name: Get initial token
      shell: |
        scylla-manager-agent download-files -L {{ backup_location }} -n {{ host_id[inventory_hostname] }} -T {{ snapshot_tag }} --dump-tokens
      register: _initial_token

    - name: Set initial_token in scylla.yaml
      lineinfile:
        path: /etc/scylla/scylla.yaml
        regexp: '^(#\s*)?initial_token:'
        line: "initial_token: {{ _initial_token.stdout }}"
        create: yes

    - name: Make each node a seed
      lineinfile:
        path: /etc/scylla/scylla.yaml
        regexp: '^(\s+) - seeds:'
        line: |
          \g<1> - seeds: {{ groups.all | join(',') }}
        backrefs: yes

    - name: Start Scylla service
      service:
        name: scylla-server
        state: started

    - name: Wait for CQL port
      wait_for:
        port: 9042

    - name: Stop Scylla service
      service:
        name: scylla-server
        state: stopped

- name: Restore schema
  hosts: all[0]
  become: true
  gather_facts: false
  tasks:
    - name: Remove other seeds
      lineinfile:
        path: /etc/scylla/scylla.yaml
        regexp: '^(\s+) - seeds:'
        line: |
          \g<1> - seeds: {{ inventory_hostname }}
        backrefs: yes

    - name: Download system_schema
      shell: |
        scylla-manager-agent download-files -L {{ backup_location }} -n {{ host_id[inventory_hostname] }} -T {{ snapshot_tag }} -d /var/lib/scylla/data/ -K system_schema --silent
      become_user: scylla

    - name: Start Scylla service
      service:
        name: scylla-server
        state: started

- name: Restore data
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Start Scylla service
      service:
        name: scylla-server
        state: started

    - name: Wait for CQL port
      wait_for:
        port: 9042

    - name: Stop Scylla service
      service:
        name: scylla-server
        state: stopped

    - name: Download data
      shell: |
        scylla-manager-agent download-files -L {{ backup_location }} -n {{ host_id[inventory_hostname] }} -T {{ snapshot_tag }} -d /var/lib/scylla/data/ -K '*,!system_schema' --silent
      become_user: scylla
      async: 86400
      poll: 5

    - name: Resore seeds list
      lineinfile:
        path: /etc/scylla/scylla.yaml
        regexp: '^(\s+) - seeds:'
        line: |
          \g<1> - seeds: {{ _seeds.stdout }}
        backrefs: yes

    - name: Start Scylla service
      service:
        name: scylla-server
        state: started
