---

# Start Scylla service
- name: Start Scylla service
  ansible.builtin.service:
    name: scylla-server
    state: started
  notify:
    - scylla-manager-agent restart
    - Enable and start 'scylla-node-exporter.service' service
  become: true

